version: '3'
services:
  app:
    build: .
    image: maayanlab/lncrnafp:1.1.4
    environment:
      - ROOT_PATH=/lncHUB2/
      - BASE_PATH=https://maayanalab.cloud
      - DEBUG=true
    ports:
      - 8080:80
