version: '3'
services:
  app:
    build: .
    image: maayanlab/lncrnafp:0.0.6
    environment:
      - ROOT_PATH=/lncrnafp/
      - BASE_PATH=https://maayanalab.cloud
      - DEBUG=true
    ports:
      - 8080:8080
