version: '3'
services:
  app:
    platform: linux/x86_64
    build: .
    image: maayanalab/lncrnafp:2.0.3
    environment:
      - ROOT_PATH=/lncHUB2/
      - BASE_PATH=https://maayanalab.cloud
      - DEBUG=true
    ports:
      - 8080:80
